name: Upload File

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Upload example.txt
      uses: actions/upload-artifact@v3
      with:
        name: example-file
        path: example.txt
