name: Upload and Download Artifact

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Upload example.txt
      uses: actions/upload-artifact@v3
      with:
        name: example-file
        path: example.txt

  download:
    runs-on: ubuntu-latest
    needs: upload

    steps:
    - name: Download example-file artifact
      uses: actions/download-artifact@v3
      with:
        name: example-file

    - name: List downloaded files
      run: ls -al
