name: Upload and Download Artifact

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Upload example.txt
      uses: actions/upload-artifact@v4
      with:
        name: filer
        path: filer/**

  download:
    runs-on: ubuntu-latest
    needs: upload

    steps:
    - name: Download example-file artifact
      uses: actions/download-artifact@v4
      with:
        name: filer

    - name: List downloaded files
      run: ls -al
